version: "3.9"
services:
  web:
    build: .
    ports:
      - "8910:8000"
    depends_on:
      postgres:
         condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://pguser:pgpass@0.0.0.0:54321/appdb
      - APP_PORT=8000
    networks:
      - backend
  postgres:
    image: "postgres:13.3"
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 12s
    ports:
      - "54321:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  backend:
    driver: "bridge"