version: "3.9"
services:
  web:
    build: .
    ports:
      - "8910:8000"
    depends_on:
      db:
         condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@0.0.0.0:5445/postgres
      - APP_PORT=8000
    networks:
      - backend
  db:
    image: "postgres:13.3"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: -p 5432
    user: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres", "-p", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    expose:
      - "5445"
    ports:
      - "5445:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  backend:
    driver: "bridge"